# Generated by Django 4.2.30 on 2026-04-14 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated list of amenities')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('floor', models.PositiveIntegerField(choices=[(1, 'Floor 1'), (2, 'Floor 2'), (3, 'Floor 3'), (4, 'Floor 4'), (5, 'Floor 5'), (6, 'Floor 6'), (7, 'Floor 7'), (8, 'Floor 8'), (9, 'Floor 9'), (10, 'Floor 10'), (11, 'Floor 11'), (12, 'Floor 12'), (13, 'Floor 13'), (14, 'Floor 14'), (15, 'Floor 15'), (16, 'Floor 16'), (17, 'Floor 17'), (18, 'Floor 18'), (19, 'Floor 19'), (20, 'Floor 20')], default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Under Maintenance'), ('cleaning', 'Being Cleaned'), ('reserved', 'Reserved')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_smoking', models.BooleanField(default=False)),
                ('has_view', models.BooleanField(default=False)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override base price for this specific room', max_digits=10, null=True)),
                ('last_cleaned', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='rooms.room')),
            ],
        ),
    ]
