# Generated by Django 4.2.30 on 2026-04-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_pricingrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ['priority']},
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('percentage_adjustment', 'Percentage Adjustment'), ('fixed_amount_adjustment', 'Fixed Amount Adjustment'), ('override_rate', 'Override Rate')], default='percentage_adjustment', max_length=30),
        ),
    ]
